image: registry.hypriot.com/armbuildchain/drone_builder_base
git:
  path: github.com/hypriot/cluster-lab
script:
  - make
  - echo -e "#####################\n***** COMPLETED *****\n#####################"
publish:
  s3:
    acl: public-read
    region: $$AWS_DEFAULT_REGION
    bucket: $$AWS_BUCKET
    access_key: $$AWS_ACCESS_KEY_ID
    secret_key: $$AWS_SECRET_ACCESS_KEY
    source: $$BUILD_RESULTS
    target: $$S3_PREFIX
    recursive: true
notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    on_started: false
    on_success: true
    on_failure: true

